_target_: src.models.transformer_module.TransformerLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

encoder:
  _target_: src.models.transformer.model.encoder.Encoder  
  input_dim: 100
  vocab_size: 784
  d_ff: 12
  d_model: 12
  num_layers: 8
  output_size: 10

decoder:
  _target_: src.models.transformer.model.decoder.Decoder
  d_ff: 12
  d_model: 12
  num_layers: 8
  max_length: 256

# compile model for faster training with pytorch 2.0
compile: false

pad_id: 0
sos_id: -1
eos_id: -2

teacher_forcing_ratio: 0.6
