_target_: src.models.transformer_module.TransformerLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

encoder:
  _target_: src.models.transformer.model.encoder.Encoder  
  vocab_size: 784
  input_dim: 100
  d_ff: 1024
  d_model: 512
  num_heads: 8
  num_layers: 4
  dropout_p: 0.1

decoder:
  _target_: src.models.transformer.model.decoder.Decoder
  vocab_size: 784
  input_dim: 100
  d_ff: 1024
  d_model: 512
  num_heads: 8
  num_layers: 8
  dropout_p: 0.1
  max_length: 256
  pad_id: 2
  sos_id: 0
  eos_id: 1

# compile model for faster training with pytorch 2.0
compile: false

pad_id: 2
sos_id: 0
eos_id: 1

teacher_forcing_ratio: 0.6
